import { beforeEach, describe, expect, it, vi } from "vitest";
import { hash, Keypair, StrKey, xdr } from "@stellar/stellar-sdk";
import { SideraClient } from "../src/client.js";
import { InvalidNameError, NameNotFoundError, NameTakenError, SideraError } from "../src/errors.js";
import type { SideraConfig } from "../src/types.js";

// Real, checksum-valid strkeys generated by the SDK — the SDK rejects
// fabricated strings, which is correct behavior.
const OWNER = Keypair.random().publicKey();
const OTHER = Keypair.random().publicKey();
const CONTRACT_ID = StrKey.encodeContract(hash(Buffer.from("sidera-test-contract")));

const CONFIG: SideraConfig = {
  contractId: CONTRACT_ID,
  network: "testnet",
};

// Stub the RPC server the client constructs; transaction builders are real
// (stellar-base), so serialization assertions run against genuine XDR.
vi.mock("@stellar/stellar-sdk", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@stellar/stellar-sdk")>();
  return {
    ...actual,
    rpc: {
      ...actual.rpc,
      Server: vi.fn().mockImplementation(() => ({
        simulateTransaction: vi.fn(),
        getAccount: vi.fn(),
        sendTransaction: vi.fn(),
      })),
    },
  };
});

function makeClient(): { client: SideraClient; server: any } {
  const client = new SideraClient(CONFIG);
  const server = (client as any).server;
  return { client, server };
}

/** Build a real ScVal map retval shaped like the contract's Resolution. */
function resolutionScVal(memo: string | null) {
  const entry = (k: string, v: xdr.ScVal) =>
    new xdr.ScMapEntry({ key: xdr.ScVal.scvString(k), val: v });
  return xdr.ScVal.scvMap([
    entry("address", xdr.ScVal.scvString(OWNER)),
    entry("owner", xdr.ScVal.scvString(OTHER)),
    entry("memo", memo == null ? xdr.ScVal.scvVec([]) : xdr.ScVal.scvVec([xdr.ScVal.scvString(memo)])),
  ]);
}

describe("SideraClient construction", () => {
  it("rejects non-contract IDs", () => {
    expect(() => new SideraClient({ ...CONFIG, contractId: "GABC" })).toThrow(SideraError);
  });

  it("rejects unknown networks without a passphrase", () => {
    expect(() => new SideraClient({ ...CONFIG, network: "customnet" })).toThrow(/Unknown network/);
  });

  it("accepts a custom rpcUrl + passphrase with any network name", () => {
    expect(
      () =>
        new SideraClient({
          ...CONFIG,
          network: "customnet",
          rpcUrl: "http://localhost:8000",
          passphrase: "Custom Net ; September 2026",
        }),
    ).not.toThrow();
  });

  it("rejects a custom network name without a passphrase", () => {
    expect(
      () =>
        new SideraClient({
          ...CONFIG,
          network: "customnet",
          rpcUrl: "http://localhost:8000",
        }),
    ).toThrow(/Unknown network/);
  });
});

describe("parameter serialization", () => {
  beforeEach(() => vi.clearAllMocks());

  it("normalizes name.sid input into a bare name in the real XDR", async () => {
    const { client, server } = makeClient();
    const simulate = server.simulateTransaction.mockResolvedValue({
      result: { retval: xdr.ScVal.scvBool(true) },
    });

    await client.exists("Alice.SID");

    expect(simulate).toHaveBeenCalledTimes(1);
    const tx = simulate.mock.calls[0][0];
    const hf = tx.operations[0].func.value();
    expect(hf.functionName().toString()).toBe("exists");
    // The contract receives the normalized bare name, not the pretty form.
    expect(hf.args()[0].str().toString()).toBe("alice");
  });

  it("rejects invalid names client-side without an RPC round-trip", async () => {
    const { client, server } = makeClient();
    await expect(client.exists("-bad")).rejects.toBeInstanceOf(InvalidNameError);
    expect(server.simulateTransaction).not.toHaveBeenCalled();
  });

  it("builds register with the owner's address ScVals and an Option memo", async () => {
    const { server } = makeClient();
    const getAccount = server.getAccount.mockResolvedValue({
      sequenceNumber: () => "1",
      accountId: () => OWNER,
      incrementSequenceNumber: () => {},
    });

    const clientWithSigner = new SideraClient({
      ...CONFIG,
      signer: { signTx: async (xdr) => xdr },
    });
    (clientWithSigner as any).server.getAccount = getAccount;
    (clientWithSigner as any).server.sendTransaction = server.sendTransaction.mockResolvedValue({
      hash: "abc123",
      status: "PENDING",
    });

    const hash = await clientWithSigner.register(
      { name: "alice", owner: OWNER, address: OWNER, memo: "1029384756" },
      {},
    );

    expect(hash).toBe("abc123");
    expect(getAccount).toHaveBeenCalledWith(OWNER);
  });
});

describe("response decoding and error mapping", () => {
  beforeEach(() => vi.clearAllMocks());

  it("maps simulation error #1 to NameNotFoundError", async () => {
    const { client, server } = makeClient();
    server.simulateTransaction.mockResolvedValue({
      error: "Error(Contract, #1)",
    });

    await expect(client.resolve("ghost")).rejects.toBeInstanceOf(NameNotFoundError);
  });

  it("maps simulation error #2 to NameTakenError", async () => {
    const { client, server } = makeClient();
    server.simulateTransaction.mockResolvedValue({
      error: "Error(Contract, #2)",
    });

    await expect(client.resolve("taken")).rejects.toBeInstanceOf(NameTakenError);
  });

  it("decodes a full resolution record: address, owner, and parsed memo", async () => {
    const { client, server } = makeClient();
    server.simulateTransaction.mockResolvedValue({
      result: { retval: resolutionScVal("1029384756") },
    });

    const res = await client.resolve("alice");
    expect(res.fullName).toBe("alice.sid");
    expect(res.address).toBe(OWNER);
    expect(res.owner).toBe(OTHER);
    expect(res.memo).toEqual({ type: "id", value: "1029384756" });
  });

  it("resolves with memo: null when the Option is empty", async () => {
    const { client, server } = makeClient();
    server.simulateTransaction.mockResolvedValue({
      result: { retval: resolutionScVal(null) },
    });

    const res = await client.resolve("alice");
    expect(res.memo).toBeNull();
    expect(res.address).toBe(OWNER);
  });

  it("treats a void retval as NameNotFound", async () => {
    const { client, server } = makeClient();
    server.simulateTransaction.mockResolvedValue({
      result: { retval: xdr.ScVal.scvVoid() },
    });

    await expect(client.resolve("ghost")).rejects.toBeInstanceOf(NameNotFoundError);
  });
});

describe("write path safety", () => {
  beforeEach(() => vi.clearAllMocks());

  it("refuses to submit transactions without a signer — before any RPC", async () => {
    const { client, server } = makeClient();
    await expect(
      client.register({
        name: "alice",
        owner: OWNER,
        address: OWNER,
      }),
    ).rejects.toThrow(/without a signer/);
    expect(server.getAccount).not.toHaveBeenCalled();
  });

  it("maps a failed transaction result carrying contract error #2 to NameTakenError", async () => {
    const { server } = makeClient();
    server.getAccount.mockResolvedValue({
      sequenceNumber: () => "1",
      accountId: () => OWNER,
      incrementSequenceNumber: () => {},
    });

    const clientWithSigner = new SideraClient({
      ...CONFIG,
      signer: { signTx: async (xdr) => xdr },
    });
    (clientWithSigner as any).server.getAccount = server.getAccount;
    (clientWithSigner as any).server.sendTransaction = server.sendTransaction.mockResolvedValue({
      hash: "",
      status: "FAILED",
      // Duck-typed xdr.TransactionResult exercising the client's traversal:
      errorResult: {
        result: () => ({
          switch: () => ({ name: "txFailed" }),
          failed: () => [
            {
              tr: () => ({
                switch: () => ({ name: "invokeHostFn" }),
                invokeHostFnResult: () => ({
                  value: () => ({
                    switch: () => ({ name: "contract" }),
                    error: () => ({ value: () => 2 }),
                  }),
                }),
              }),
            },
          ],
        }),
      },
    });

    await expect(
      clientWithSigner.register({ name: "alice", owner: OWNER, address: OWNER }),
    ).rejects.toBeInstanceOf(NameTakenError);
  });
});

describe("memo integration", () => {
  it("ResolutionResult.memo is wallet-ready via toStellarMemo", async () => {
    const { toStellarMemo } = await import("../src/memo.js");
    const memo = toStellarMemo({ type: "id", value: "1029384756" });
    expect(memo.type).toBe("id");
    expect(memo.value).toBe("1029384756");
  });
});
